//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.TransIp.Models;

#nullable enable

namespace Apigen.TransIp.Client;

/// <summary>
/// Interface for Actions operations
/// </summary>
public partial interface IActionsClient
{
  /// <summary>
  /// List all actions
  /// Operation: GET /actions
  /// </summary>
  Task<JsonElement> ListAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get action by uuid
  /// Operation: GET /actions/{uuid}
  /// </summary>
  Task<JsonElement> GetAsync(string uuid, CancellationToken cancellationToken = default);

  /// <summary>
  /// List all child actions for a parent action
  /// Operation: GET /actions/{uuid}/children
  /// </summary>
  Task<JsonElement> ListAllChildActionsParentAsync(string uuid, CancellationToken cancellationToken = default);

}
