//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.TransIp.Models;

#nullable enable

namespace Apigen.TransIp.Client;

/// <summary>
/// Interface for Email operations
/// </summary>
public partial interface IEmailClient
{
  /// <summary>
  /// List all mail packages
  /// Operation: GET /email
  /// </summary>
  Task<JsonElement> GetAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// List all mail addons
  /// Operation: GET /email/{domain}/mail-addons
  /// </summary>
  Task<JsonElement> ListAllMailAddonsAsync(string domain, CancellationToken cancellationToken = default);

  /// <summary>
  /// Unlink email addon to mailbox
  /// Operation: PATCH /email/{domain}/mail-addons/{id}
  /// </summary>
  Task<JsonElement> UnlinkEmailAddonMailboxAsync(string domain, string id, Apigen.TransIp.Models.UnlinkEmailAddonMailboxRequest unlinkEmailAddonMailboxRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List all mail forwards
  /// Operation: GET /email/{domain}/mail-forwards
  /// </summary>
  Task<JsonElement> ListAllMailForwardsAsync(string domain, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create mail forward
  /// Operation: POST /email/{domain}/mail-forwards
  /// </summary>
  Task<JsonElement> CreateMailForwardAsync(string domain, Apigen.TransIp.Models.CreateMailForwardRequest createMailForwardRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete mail forward
  /// Operation: DELETE /email/{domain}/mail-forwards/{forwardId}
  /// </summary>
  Task DeleteMailForwardAsync(string domain, string forwardId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mail forward
  /// Operation: GET /email/{domain}/mail-forwards/{forwardId}
  /// </summary>
  Task<JsonElement> GetMailForwardAsync(string domain, string forwardId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update mail forward field
  /// Operation: PATCH /email/{domain}/mail-forwards/{forwardId}
  /// </summary>
  Task UpdateMailForwardFieldAsync(string domain, string forwardId, Apigen.TransIp.Models.UpdateMailForwardFieldRequest updateMailForwardFieldRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update mail forward
  /// Operation: PUT /email/{domain}/mail-forwards/{forwardId}
  /// </summary>
  Task UpdateMailForwardAsync(string domain, string forwardId, Apigen.TransIp.Models.UpdateMailForwardRequest updateMailForwardRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List all Mail lists
  /// Operation: GET /email/{domain}/mail-lists
  /// </summary>
  Task<JsonElement> ListAllMailListsAsync(string domain, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create Mail list
  /// Operation: POST /email/{domain}/mail-lists
  /// </summary>
  Task CreateMailListAsync(string domain, Apigen.TransIp.Models.CreateMailListRequest createMailListRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Mail List
  /// Operation: DELETE /email/{domain}/mail-lists/{listId}
  /// </summary>
  Task DeleteMailListAsync(string domain, string listId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Mail list
  /// Operation: GET /email/{domain}/mail-lists/{listId}
  /// </summary>
  Task<JsonElement> GetMailListAsync(string domain, string listId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Mail list
  /// Operation: PUT /email/{domain}/mail-lists/{listId}
  /// </summary>
  Task UpdateMailListAsync(string domain, string listId, Apigen.TransIp.Models.UpdateMailListRequest updateMailListRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List all Mailboxes
  /// Operation: GET /email/{domain}/mailboxes
  /// </summary>
  Task<JsonElement> ListAllMailboxesAsync(string domain, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create Mailbox
  /// Operation: POST /email/{domain}/mailboxes
  /// </summary>
  Task<JsonElement> CreateMailboxAsync(string domain, Apigen.TransIp.Models.CreateMailboxRequest createMailboxRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Mailbox
  /// Operation: DELETE /email/{domain}/mailboxes/{identifier}
  /// </summary>
  Task<JsonElement> DeleteMailboxAsync(string domain, string identifier, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Mailbox
  /// Operation: GET /email/{domain}/mailboxes/{identifier}
  /// </summary>
  Task<JsonElement> GetMailboxAsync(string domain, string identifier, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Mailbox field
  /// Operation: PATCH /email/{domain}/mailboxes/{identifier}
  /// </summary>
  Task<JsonElement> UpdateMailboxFieldAsync(string domain, string identifier, Apigen.TransIp.Models.UpdateMailboxFieldRequest updateMailboxFieldRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Mailbox
  /// Operation: PUT /email/{domain}/mailboxes/{identifier}
  /// </summary>
  Task<JsonElement> UpdateMailboxAsync(string domain, string identifier, Apigen.TransIp.Models.UpdateMailboxRequest updateMailboxRequest, CancellationToken cancellationToken = default);

}
