//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.TransIp.Models;

#nullable enable

namespace Apigen.TransIp.Client;

/// <summary>
/// Interface for General operations
/// </summary>
public partial interface IGeneralClient
{
  /// <summary>
  /// API Test
  /// Operation: GET /api-test
  /// </summary>
  Task<JsonElement> ApiTestAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// List available AvailabilityZones
  /// Operation: GET /availability-zones
  /// </summary>
  Task<JsonElement> ListAvailableAvailabilityZonesAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// List all products
  /// Operation: GET /products
  /// </summary>
  Task<JsonElement> ListAllProductsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// List specifications for product
  /// Operation: GET /products/{productName}/elements
  /// </summary>
  Task<JsonElement> ListSpecificationsProductAsync(string productName, CancellationToken cancellationToken = default);

}
