// This file is hand-written and is NOT regenerated by the apigen-dotnet generator.
// It exchanges a TransIP API private key for a short-lived JWT bearer token using
// only .NET BCL APIs (RSA + HttpClient + System.Text.Json) — no third-party crypto.
//
// See: https://api.transip.nl/rest/docs.html#header-authentication

using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace Apigen.Transip.Client;

/// <summary>
/// Async delegate that returns a valid TransIP JWT bearer token for use in an
/// <c>Authorization: Bearer …</c> header. Implementations are responsible for
/// caching, expiry tracking, and acquiring fresh tokens as needed.
/// </summary>
public delegate ValueTask<string> TransipTokenAccessor(CancellationToken cancellationToken = default);

/// <summary>
/// Exchanges a TransIP API private key for a short-lived JWT bearer token.
/// </summary>
public static class TransipAuthTokenProvider
{
  public const string DefaultBaseUrl = "https://api.transip.nl/v6";
  public const string DefaultExpirationTime = "1 day";
  private const string AuthPath = "auth";

  private static readonly TimeSpan s_defaultRefreshBefore = TimeSpan.FromMinutes(5);

  // Serialize all fields (including false booleans) so the request body matches
  // the shape documented at https://api.transip.nl/rest/docs.html#header-authentication
  private static readonly JsonSerializerOptions s_jsonOptions = new()
  {
    Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
  };

  /// <summary>
  /// Build a token accessor that lazily acquires a JWT and caches it in memory
  /// until it is within <paramref name="refreshBefore"/> of expiry, at which
  /// point the next call performs a fresh authentication. Thread-safe; concurrent
  /// callers during a refresh share a single in-flight request.
  /// </summary>
  /// <param name="login">TransIP account name.</param>
  /// <param name="privateKeyPem">PKCS#8 PEM private key from the TransIP control panel.</param>
  /// <param name="label">Optional token label. A unique value is generated if omitted.</param>
  /// <param name="readOnly">Request a read-only token.</param>
  /// <param name="expirationTime">Lifetime, e.g. "30 minutes", "1 hour", "1 day". Max 1 month.</param>
  /// <param name="globalKey">Allow use from any IP address.</param>
  /// <param name="baseUrl">Base URL of the TransIP API.</param>
  /// <param name="refreshBefore">Acquire a new token this far before expiry. Default: 5 minutes.</param>
  /// <param name="httpClientFactory">Optional factory for the HttpClient used to call /auth.
  /// If null, a transient HttpClient is created per auth call.</param>
  /// <param name="logger">Optional logger for auth events.</param>
  public static TransipTokenAccessor CreateAccessor(
    string login,
    string privateKeyPem,
    string? label = null,
    bool readOnly = false,
    string expirationTime = DefaultExpirationTime,
    bool globalKey = false,
    string baseUrl = DefaultBaseUrl,
    TimeSpan? refreshBefore = null,
    Func<HttpClient>? httpClientFactory = null,
    ILogger? logger = null)
  {
    if (string.IsNullOrWhiteSpace(login)) throw new ArgumentException("login is required", nameof(login));
    if (string.IsNullOrWhiteSpace(privateKeyPem)) throw new ArgumentException("privateKeyPem is required", nameof(privateKeyPem));

    TimeSpan margin = refreshBefore ?? s_defaultRefreshBefore;

    CachedToken? cached = null;
    SemaphoreSlim gate = new(1, 1);

    return async (cancellationToken) =>
    {
      // Fast path: usable cached token, no lock.
      CachedToken? snapshot = cached;
      if (snapshot != null && snapshot.IsUsable(margin))
      {
        return snapshot.Jwt;
      }

      await gate.WaitAsync(cancellationToken).ConfigureAwait(false);
      try
      {
        // Re-check after acquiring the lock — another caller may have refreshed.
        snapshot = cached;
        if (snapshot != null && snapshot.IsUsable(margin))
        {
          return snapshot.Jwt;
        }

        logger?.LogDebug("Acquiring new TransIP JWT for login '{Login}'", login);
        (string jwt, DateTimeOffset expiresAt) = await GetBearerTokenAsync(
          login, privateKeyPem, label, readOnly, expirationTime, globalKey,
          baseUrl, httpClientFactory?.Invoke(), cancellationToken).ConfigureAwait(false);

        cached = new CachedToken(jwt, expiresAt);
        logger?.LogDebug("Acquired TransIP JWT for login '{Login}', expires at {ExpiresAt:o}", login, expiresAt);
        return jwt;
      }
      finally
      {
        gate.Release();
      }
    };
  }

  /// <summary>
  /// Build a fully-configured <see cref="TransipApiClient"/> backed by an
  /// in-memory token cache that automatically re-authenticates before expiry.
  /// Suitable for singleton registration in DI containers.
  /// </summary>
  public static TransipApiClient CreateClient(
    string login,
    string privateKeyPem,
    string? label = null,
    bool readOnly = false,
    string expirationTime = DefaultExpirationTime,
    bool globalKey = false,
    string baseUrl = DefaultBaseUrl,
    TimeSpan? refreshBefore = null,
    ILogger? logger = null)
  {
    TransipTokenAccessor accessor = CreateAccessor(
      login, privateKeyPem, label, readOnly, expirationTime, globalKey, baseUrl, refreshBefore, logger: logger);

    string normalizedBaseUrl = baseUrl.EndsWith('/') ? baseUrl : baseUrl + "/";
    HttpClient httpClient = new(new TransipBearerHandler(accessor) { InnerHandler = new HttpClientHandler() })
    {
      BaseAddress = new Uri(normalizedBaseUrl),
    };

    return new TransipApiClient(httpClient, logger);
  }

  /// <summary>
  /// One-shot token exchange. Returns the raw JWT and its parsed expiry time.
  /// Performs no caching; each call hits <c>/v6/auth</c>.
  /// </summary>
  public static async Task<(string Jwt, DateTimeOffset ExpiresAt)> GetBearerTokenAsync(
    string login,
    string privateKeyPem,
    string? label = null,
    bool readOnly = false,
    string expirationTime = DefaultExpirationTime,
    bool globalKey = false,
    string baseUrl = DefaultBaseUrl,
    HttpClient? httpClient = null,
    CancellationToken cancellationToken = default)
  {
    if (string.IsNullOrWhiteSpace(login)) throw new ArgumentException("login is required", nameof(login));
    if (string.IsNullOrWhiteSpace(privateKeyPem)) throw new ArgumentException("privateKeyPem is required", nameof(privateKeyPem));

    AuthRequest payload = new()
    {
      Login = login,
      Nonce = GenerateNonce(),
      ReadOnly = readOnly,
      ExpirationTime = expirationTime,
      Label = label ?? $"apigen-dotnet-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
      GlobalKey = globalKey,
    };

    byte[] body = JsonSerializer.SerializeToUtf8Bytes(payload, s_jsonOptions);
    string signature = SignBody(body, privateKeyPem);

    string url = baseUrl.TrimEnd('/') + "/" + AuthPath;

    HttpClient client = httpClient ?? new HttpClient();
    bool ownsClient = httpClient is null;
    try
    {
      using HttpRequestMessage request = new(HttpMethod.Post, url);
      request.Content = new ByteArrayContent(body);
      request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
      request.Headers.TryAddWithoutValidation("Signature", signature);

      using HttpResponseMessage response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
      string responseBody = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

      if (!response.IsSuccessStatusCode)
      {
        throw new TransipAuthException(
          $"TransIP authentication failed with status {(int)response.StatusCode} {response.ReasonPhrase}: {responseBody}",
          response.StatusCode,
          responseBody);
      }

      AuthResponse? parsed = JsonSerializer.Deserialize<AuthResponse>(responseBody);
      if (parsed is null || string.IsNullOrEmpty(parsed.Token))
      {
        throw new TransipAuthException(
          $"TransIP authentication response did not contain a token: {responseBody}",
          response.StatusCode,
          responseBody);
      }

      DateTimeOffset expiresAt = ExtractJwtExpiry(parsed.Token)
        ?? DateTimeOffset.UtcNow.Add(ParseExpirationTime(expirationTime));

      return (parsed.Token, expiresAt);
    }
    finally
    {
      if (ownsClient) client.Dispose();
    }
  }

  /// <summary>
  /// Parse the <c>exp</c> claim from a JWT without validating its signature.
  /// Returns <c>null</c> if the token can't be parsed.
  /// </summary>
  private static DateTimeOffset? ExtractJwtExpiry(string jwt)
  {
    string[] parts = jwt.Split('.');
    if (parts.Length != 3) return null;

    try
    {
      byte[] payload = Base64UrlDecode(parts[1]);
      using JsonDocument doc = JsonDocument.Parse(payload);
      if (doc.RootElement.TryGetProperty("exp", out JsonElement exp) && exp.TryGetInt64(out long unix))
      {
        return DateTimeOffset.FromUnixTimeSeconds(unix);
      }
    }
    catch
    {
      // Fall through to null — caller will use the requested expirationTime as a fallback.
    }
    return null;
  }

  private static byte[] Base64UrlDecode(string input)
  {
    string padded = input.Replace('-', '+').Replace('_', '/');
    switch (padded.Length % 4)
    {
      case 2: padded += "=="; break;
      case 3: padded += "="; break;
    }
    return Convert.FromBase64String(padded);
  }

  /// <summary>
  /// Convert a TransIP-style expirationTime string ("30 minutes", "1 hour", "1 day", …)
  /// to a TimeSpan. Used as a fallback when the JWT exp claim can't be read.
  /// </summary>
  private static TimeSpan ParseExpirationTime(string expirationTime)
  {
    string[] parts = expirationTime.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);
    if (parts.Length == 2 && int.TryParse(parts[0], out int n))
    {
      return parts[1].ToLowerInvariant() switch
      {
        "second" or "seconds" => TimeSpan.FromSeconds(n),
        "minute" or "minutes" => TimeSpan.FromMinutes(n),
        "hour" or "hours" => TimeSpan.FromHours(n),
        "day" or "days" => TimeSpan.FromDays(n),
        "week" or "weeks" => TimeSpan.FromDays(n * 7),
        "month" or "months" => TimeSpan.FromDays(n * 30),
        _ => TimeSpan.FromMinutes(30),
      };
    }
    return TimeSpan.FromMinutes(30);
  }

  private static string SignBody(byte[] body, string privateKeyPem)
  {
    using RSA rsa = RSA.Create();
    try
    {
      rsa.ImportFromPem(privateKeyPem);
    }
    catch (Exception ex) when (ex is ArgumentException or CryptographicException)
    {
      throw new TransipAuthException(
        "Failed to import TransIP private key. The key must be a PEM-encoded PKCS#8 or PKCS#1 RSA private key.",
        null, null, ex);
    }

    byte[] signature = rsa.SignData(body, HashAlgorithmName.SHA512, RSASignaturePadding.Pkcs1);
    return Convert.ToBase64String(signature);
  }

  private static string GenerateNonce()
  {
    Span<byte> bytes = stackalloc byte[12];
    RandomNumberGenerator.Fill(bytes);
    return Convert.ToHexString(bytes).ToLowerInvariant();
  }

  private sealed class CachedToken
  {
    public string Jwt { get; }
    public DateTimeOffset ExpiresAt { get; }

    public CachedToken(string jwt, DateTimeOffset expiresAt)
    {
      Jwt = jwt;
      ExpiresAt = expiresAt;
    }

    public bool IsUsable(TimeSpan refreshBefore) =>
      DateTimeOffset.UtcNow < ExpiresAt - refreshBefore;
  }

  private sealed class AuthRequest
  {
    [JsonPropertyName("login")]
    public string Login { get; set; } = "";

    [JsonPropertyName("nonce")]
    public string Nonce { get; set; } = "";

    [JsonPropertyName("read_only")]
    public bool ReadOnly { get; set; }

    [JsonPropertyName("expiration_time")]
    public string ExpirationTime { get; set; } = "";

    [JsonPropertyName("label")]
    public string Label { get; set; } = "";

    [JsonPropertyName("global_key")]
    public bool GlobalKey { get; set; }
  }

  private sealed class AuthResponse
  {
    [JsonPropertyName("token")]
    public string? Token { get; set; }
  }
}

/// <summary>
/// HttpMessageHandler that injects a TransIP Bearer token on every outgoing
/// request via the supplied <see cref="TransipTokenAccessor"/>. The accessor
/// is responsible for caching and refresh-before-expiry; this handler simply
/// asks for a valid token per request.
/// </summary>
public sealed class TransipBearerHandler : DelegatingHandler
{
  private readonly TransipTokenAccessor _accessor;

  public TransipBearerHandler(TransipTokenAccessor accessor)
  {
    _accessor = accessor ?? throw new ArgumentNullException(nameof(accessor));
  }

  public TransipBearerHandler(TransipTokenAccessor accessor, HttpMessageHandler innerHandler)
    : base(innerHandler)
  {
    _accessor = accessor ?? throw new ArgumentNullException(nameof(accessor));
  }

  protected override async Task<HttpResponseMessage> SendAsync(
    HttpRequestMessage request, CancellationToken cancellationToken)
  {
    string token = await _accessor(cancellationToken).ConfigureAwait(false);
    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
    return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
  }
}

/// <summary>Thrown when the TransIP authentication endpoint rejects a request.</summary>
public sealed class TransipAuthException : Exception
{
  public System.Net.HttpStatusCode? StatusCode { get; }
  public string? ResponseBody { get; }

  public TransipAuthException(string message, System.Net.HttpStatusCode? statusCode, string? responseBody, Exception? inner = null)
    : base(message, inner)
  {
    StatusCode = statusCode;
    ResponseBody = responseBody;
  }
}
