// This file is hand-written and is NOT regenerated by the apigen-dotnet generator.
// It exchanges a TransIP API private key for a short-lived JWT bearer token using
// only .NET BCL APIs (RSA + HttpClient + System.Text.Json) — no third-party crypto.
//
// See: https://api.transip.nl/rest/docs.html#header-authentication

using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Apigen.Transip.Client;

/// <summary>
/// Exchanges a TransIP API private key for a short-lived JWT bearer token.
/// </summary>
public static class TransipAuthTokenProvider
{
  public const string DefaultBaseUrl = "https://api.transip.nl/v6";
  private const string AuthPath = "auth";

  // Serialize all fields (including false booleans) so the request body matches the
  // shape documented at https://api.transip.nl/rest/docs.html#header-authentication
  private static readonly JsonSerializerOptions s_jsonOptions = new()
  {
    Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
  };

  /// <summary>
  /// Exchange a private key for a JWT bearer token.
  /// </summary>
  /// <param name="login">TransIP account name.</param>
  /// <param name="privateKeyPem">PKCS#8 PEM private key from the TransIP control panel.</param>
  /// <param name="label">Optional token label. A unique value is generated if omitted.</param>
  /// <param name="readOnly">Request a read-only token.</param>
  /// <param name="expirationTime">Lifetime, e.g. "30 minutes", "1 hour", "1 day". Max 1 month.</param>
  /// <param name="globalKey">Allow use from any IP address.</param>
  /// <param name="baseUrl">Base URL of the TransIP API.</param>
  /// <param name="httpClient">Optional HttpClient to use for the auth call. A transient one is created if null.</param>
  /// <param name="cancellationToken">Cancellation token.</param>
  /// <returns>The JWT bearer token string (without the "Bearer " prefix).</returns>
  public static async Task<string> GetBearerTokenAsync(
    string login,
    string privateKeyPem,
    string? label = null,
    bool readOnly = false,
    string expirationTime = "30 minutes",
    bool globalKey = false,
    string baseUrl = DefaultBaseUrl,
    HttpClient? httpClient = null,
    CancellationToken cancellationToken = default)
  {
    if (string.IsNullOrWhiteSpace(login)) throw new ArgumentException("login is required", nameof(login));
    if (string.IsNullOrWhiteSpace(privateKeyPem)) throw new ArgumentException("privateKeyPem is required", nameof(privateKeyPem));

    AuthRequest payload = new()
    {
      Login = login,
      Nonce = GenerateNonce(),
      ReadOnly = readOnly,
      ExpirationTime = expirationTime,
      Label = label ?? $"apigen-dotnet-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
      GlobalKey = globalKey,
    };

    byte[] body = JsonSerializer.SerializeToUtf8Bytes(payload, s_jsonOptions);
    string signature = SignBody(body, privateKeyPem);

    string url = baseUrl.TrimEnd('/') + "/" + AuthPath;

    HttpClient client = httpClient ?? new HttpClient();
    bool ownsClient = httpClient is null;
    try
    {
      using HttpRequestMessage request = new(HttpMethod.Post, url);
      request.Content = new ByteArrayContent(body);
      request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
      request.Headers.TryAddWithoutValidation("Signature", signature);

      using HttpResponseMessage response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
      string responseBody = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

      if (!response.IsSuccessStatusCode)
      {
        throw new TransipAuthException(
          $"TransIP authentication failed with status {(int)response.StatusCode} {response.ReasonPhrase}: {responseBody}",
          response.StatusCode,
          responseBody);
      }

      AuthResponse? parsed = JsonSerializer.Deserialize<AuthResponse>(responseBody);
      if (parsed is null || string.IsNullOrEmpty(parsed.Token))
      {
        throw new TransipAuthException(
          $"TransIP authentication response did not contain a token: {responseBody}",
          response.StatusCode,
          responseBody);
      }

      return parsed.Token;
    }
    finally
    {
      if (ownsClient) client.Dispose();
    }
  }

  /// <summary>
  /// Convenience: obtain a token and return a fully-configured TransipApiClient.
  /// </summary>
  public static async Task<TransipApiClient> CreateClientAsync(
    string login,
    string privateKeyPem,
    string? label = null,
    bool readOnly = false,
    string expirationTime = "30 minutes",
    bool globalKey = false,
    string baseUrl = DefaultBaseUrl,
    Microsoft.Extensions.Logging.ILogger? logger = null,
    CancellationToken cancellationToken = default)
  {
    string token = await GetBearerTokenAsync(
      login, privateKeyPem, label, readOnly, expirationTime, globalKey, baseUrl,
      cancellationToken: cancellationToken).ConfigureAwait(false);

    return TransipApiClient.WithBearer(token, baseUrl, logger);
  }

  private static string SignBody(byte[] body, string privateKeyPem)
  {
    using RSA rsa = RSA.Create();
    try
    {
      rsa.ImportFromPem(privateKeyPem);
    }
    catch (Exception ex) when (ex is ArgumentException or CryptographicException)
    {
      throw new TransipAuthException(
        "Failed to import TransIP private key. The key must be a PEM-encoded PKCS#8 or PKCS#1 RSA private key.",
        null, null, ex);
    }

    byte[] signature = rsa.SignData(body, HashAlgorithmName.SHA512, RSASignaturePadding.Pkcs1);
    return Convert.ToBase64String(signature);
  }

  private static string GenerateNonce()
  {
    Span<byte> bytes = stackalloc byte[12];
    RandomNumberGenerator.Fill(bytes);
    return Convert.ToHexString(bytes).ToLowerInvariant();
  }

  private sealed class AuthRequest
  {
    [JsonPropertyName("login")]
    public string Login { get; set; } = "";

    [JsonPropertyName("nonce")]
    public string Nonce { get; set; } = "";

    [JsonPropertyName("read_only")]
    public bool ReadOnly { get; set; }

    [JsonPropertyName("expiration_time")]
    public string ExpirationTime { get; set; } = "";

    [JsonPropertyName("label")]
    public string Label { get; set; } = "";

    [JsonPropertyName("global_key")]
    public bool GlobalKey { get; set; }
  }

  private sealed class AuthResponse
  {
    [JsonPropertyName("token")]
    public string? Token { get; set; }
  }
}

/// <summary>Thrown when the TransIP authentication endpoint rejects a request.</summary>
public sealed class TransipAuthException : Exception
{
  public System.Net.HttpStatusCode? StatusCode { get; }
  public string? ResponseBody { get; }

  public TransipAuthException(string message, System.Net.HttpStatusCode? statusCode, string? responseBody, Exception? inner = null)
    : base(message, inner)
  {
    StatusCode = statusCode;
    ResponseBody = responseBody;
  }
}
