//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// AddLetsEncryptCertificateToHAIPRequest from OpenAPI schema.
/// Schema path: #/components/schemas/AddLetsEncryptCertificateToHAIPRequest
/// </summary>
public class AddLetsEncryptCertificateToHAIPRequest
{
  /// <summary>
  /// The domain name that the SSL certificate is added to. Start with ‘*.’ when the certificate is a wildcard
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("commonName")]
  public string? CommonName { get; set; }
}
