//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// AddLoadBalancerRequest (generated from inline request body).
/// Source: POST /kubernetes/clusters/{clusterName}/load-balancers (requestBody)
/// </summary>
public partial class AddLoadBalancerRequest
{
  /// <summary>
  /// user configurable unique identifier for loadBalancer (max 64 chars), when none is given, the uuid will be used. (cannot be changed later on)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
