//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// AddMailServiceDnsEntriesToDomainsRequest from OpenAPI schema.
/// Schema path: #/components/schemas/AddMailServiceDnsEntriesToDomainsRequest
/// </summary>
public class AddMailServiceDnsEntriesToDomainsRequest
{
  /// <summary>
  /// The domain names to which the DNS entries should be added
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("domainNames")]
  public List<object>? DomainNames { get; set; }
}
