//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// AddNodepoolRequest (generated from inline request body).
/// Source: POST /kubernetes/clusters/{clusterName}/node-pools (requestBody)
/// </summary>
public partial class AddNodepoolRequest
{
  /// <summary>
  /// Availability Zone the WorkerNodes of this pool will spawn
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// Describes the Node Pool (max 64 chars)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Amount of WorkerNodes
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("desiredNodeCount")]
  public decimal? DesiredNodeCount { get; set; }

  /// <summary>
  /// Node type for the WorkerNodes in this pool
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("nodeSpec")]
  public string? NodeSpec { get; set; }
}
