//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// Addons from OpenAPI schema.
/// Schema path: #/components/schemas/Addons
/// </summary>
public class Addons
{
  /// <summary>
  /// A list of all active addons
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("active")]
  public List<object?>? Active { get; set; }

  /// <summary>
  /// A list of available addons that you can order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("available")]
  public List<object?>? Available { get; set; }

  /// <summary>
  /// A list of addons that you can cancel
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("cancellable")]
  public List<object?>? Cancellable { get; set; }
}
