//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// AttachCustomDomainNameDiskRequest (generated from inline request body).
/// Source: POST /filehosting/disks/{diskId}/custom-domains (requestBody)
/// </summary>
public partial class AttachCustomDomainNameDiskRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("altHostname")]
  public string? AltHostname { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("domainName")]
  public decimal DomainName { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("hostname")]
  public string? Hostname { get; set; }
}
