//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// AvailabilityZone from OpenAPI schema.
/// Schema path: #/components/schemas/AvailabilityZone
/// </summary>
public partial class AvailabilityZone
{
  /// <summary>
  /// The 2 letter code for the country the AvailabilityZone is in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// If true this is the default zone new VPSes and clones are created in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isDefault")]
  public bool? IsDefault { get; set; }

  /// <summary>
  /// Name of AvailabilityZone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
