//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// BigStorageBackup from OpenAPI schema.
/// Schema path: #/components/schemas/BigStorageBackup
/// </summary>
public partial class BigStorageBackup
{
  /// <summary>
  /// The name of the availability zone the backup is in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// Date of the big storage backup
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeCreate")]
  public string? DateTimeCreate { get; set; }

  /// <summary>
  /// The backup disk size in kB
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskSize")]
  public decimal DiskSize { get; set; }

  /// <summary>
  /// Id of the big storage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal? Id { get; set; }

  /// <summary>
  /// Status of the big storage backup (&apos;active&apos;, &apos;creating&apos;, &apos;reverting&apos;, &apos;deleting&apos;, &apos;pendingDeletion&apos;, &apos;syncing&apos;, &apos;moving&apos;)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
