//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// CheckAvailabilityMultipleDomainNamesRequest (generated from inline request body).
/// Source: GET /domain-availability (requestBody)
/// </summary>
public partial class CheckAvailabilityMultipleDomainNamesRequest
{
  /// <summary>
  /// array of domainNames to check
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("domainNames")]
  public List<object>? DomainNames { get; set; }
}
