//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// Colocation from OpenAPI schema.
/// Schema path: #/components/schemas/Colocation
/// </summary>
public partial class Colocation
{
  /// <summary>
  /// List of IP ranges
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ipRanges")]
  public List<object?>? IpRanges { get; set; }

  /// <summary>
  /// Colocation name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
