//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// CreateNewClusterRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CreateNewClusterRequest
/// </summary>
public class CreateNewClusterRequest
{
  /// <summary>
  /// Availability Zone the WorkerNodes of the initial pool will spawn
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// Describes this cluster
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The desired amount of nodes in the initial NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("desiredNodeCount")]
  public decimal? DesiredNodeCount { get; set; }

  /// <summary>
  /// The specific version the Cluster should run on
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("kubernetesVersion")]
  public string? KubernetesVersion { get; set; }

  /// <summary>
  /// ProductName for the WorkerNodes in the initial NodePool; use the /kubernetes/products resource to determine which to use
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("nodeSpec")]
  public string? NodeSpec { get; set; }
}
