//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// DataCenterVisitor from OpenAPI schema.
/// Schema path: #/components/schemas/DataCenterVisitor
/// </summary>
public class DataCenterVisitor
{
  /// <summary>
  /// The accesscode of the visitor
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("accessCode")]
  public string? AccessCode { get; set; }

  /// <summary>
  /// True if this visitor been registered before at the datacenter. If true, does not need the accesscode
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasBeenRegisteredBefore")]
  public bool HasBeenRegisteredBefore { get; set; }

  /// <summary>
  /// The name of the visitor
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The reservation number of the visitor
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("reservationNumber")]
  public decimal ReservationNumber { get; set; }
}
