//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// DnsEntry from OpenAPI schema.
/// Schema path: #/components/schemas/DnsEntry
/// </summary>
public partial class DnsEntry
{
  /// <summary>
  /// The content of of the dns entry, for example &apos;10 mail&apos;, &apos;127.0.0.1&apos; or &apos;www&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("content")]
  public string? Content { get; set; }

  /// <summary>
  /// The expiration period of the dns entry, in seconds. For example 86400 for a day of expiration
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("expire")]
  public decimal Expire { get; set; }

  /// <summary>
  /// The name of the dns entry, for example &apos;@&apos; or &apos;www&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The type of dns entry. Possbible types are &apos;A&apos;, &apos;AAAA&apos;, &apos;CNAME&apos;, &apos;MX&apos;, &apos;NS&apos;, &apos;TXT&apos;, &apos;SRV&apos;, &apos;SSHFP&apos;, &apos;TLSA&apos;, &apos;CAA&apos; and &apos;NAPTR&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
