//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// DomainCheckResult from OpenAPI schema.
/// Schema path: #/components/schemas/DomainCheckResult
/// </summary>
public class DomainCheckResult
{
  /// <summary>
  /// List of available actions to perform on this domain. Possible actions are: &apos;register&apos;, &apos;transfer&apos;, &apos;internalpull&apos; and &apos;internalpush&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("actions")]
  public List<object?>? Actions { get; set; }

  /// <summary>
  /// The name of the domain
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("domainName")]
  public string? DomainName { get; set; }

  /// <summary>
  /// The status for this domain. Possible statuses are: &apos;inyouraccount&apos;, &apos;unavailable&apos;, &apos;notfree&apos;, &apos;free&apos;, &apos;internalpull&apos; and &apos;internalpush&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
