//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// DomainBranding from OpenAPI schema.
/// Schema path: #/components/schemas/DomainBranding
/// </summary>
public partial class DomainBranding
{
  /// <summary>
  /// The first generic bannerLine displayed in whois-branded whois output.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("bannerLine1")]
  public string? BannerLine1 { get; set; }

  /// <summary>
  /// The second generic bannerLine displayed in whois-branded whois output.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("bannerLine2")]
  public string? BannerLine2 { get; set; }

  /// <summary>
  /// The third generic bannerLine displayed in whois-branded whois output.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("bannerLine3")]
  public string? BannerLine3 { get; set; }

  /// <summary>
  /// The company name displayed in transfer-branded e-mails
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("companyName")]
  public string? CompanyName { get; set; }

  /// <summary>
  /// The company url displayed in transfer-branded e-mails
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("companyUrl")]
  public string? CompanyUrl { get; set; }

  /// <summary>
  /// The support email used for transfer-branded e-mails
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("supportEmail")]
  public string? SupportEmail { get; set; }

  /// <summary>
  /// The terms of usage url as displayed in transfer-branded e-mails
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("termsOfUsageUrl")]
  public string? TermsOfUsageUrl { get; set; }
}
