//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// FilehostingCustomDomainName from OpenAPI schema.
/// Schema path: #/components/schemas/FilehostingCustomDomainName
/// </summary>
public class FilehostingCustomDomainName
{
  /// <summary>
  /// Creation time of the custom domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public string? CreatedAt { get; set; }

  /// <summary>
  /// Id of the filehosting disk that owns the custom domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("diskId")]
  public decimal? DiskId { get; set; }

  /// <summary>
  /// Domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("domainName")]
  public string? DomainName { get; set; }

  /// <summary>
  /// Expiration time of the custom domain name certificate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public string? ExpiresAt { get; set; }

  /// <summary>
  /// Fully qualified domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fqdn")]
  public string? Fqdn { get; set; }

  /// <summary>
  /// Hostname
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hostname")]
  public string? Hostname { get; set; }

  /// <summary>
  /// Id of the custom domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal? Id { get; set; }

  /// <summary>
  /// Status of the custom domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
