//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// FilehostingUser from OpenAPI schema.
/// Schema path: #/components/schemas/FilehostingUser
/// </summary>
public class FilehostingUser
{
  /// <summary>
  /// The creation date &amp; time of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public string? CreatedAt { get; set; }

  /// <summary>
  /// Customized user display name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  /// <summary>
  /// Free size of the user in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("freeBytes")]
  public decimal? FreeBytes { get; set; }

  /// <summary>
  /// Id of the disk user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal? Id { get; set; }

  /// <summary>
  /// Current usage of the user in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inUseBytes")]
  public decimal? InUseBytes { get; set; }

  /// <summary>
  /// Total assigned capacity for the user in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("quotaBytes")]
  public decimal? QuotaBytes { get; set; }

  /// <summary>
  /// Total size of the user in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sizeBytes")]
  public decimal? SizeBytes { get; set; }

  /// <summary>
  /// Username of the disk user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
