//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// GetBlockStorageStatisticsRequest (generated from inline request body).
/// Source: GET /kubernetes/clusters/{clusterName}/block-storages/{name}/stats (requestBody)
/// </summary>
public partial class GetBlockStorageStatisticsRequest
{
  /// <summary>
  /// The end date of the usage statistics
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeEnd")]
  public decimal? DateTimeEnd { get; set; }

  /// <summary>
  /// The start date of the usage statistics
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeStart")]
  public decimal? DateTimeStart { get; set; }
}
