//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// HaipCertificate from OpenAPI schema.
/// Schema path: #/components/schemas/HaipCertificate
/// </summary>
public partial class HaipCertificate
{
  /// <summary>
  /// The common name of the certificate, usually a domain name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("commonName")]
  public string? CommonName { get; set; }

  /// <summary>
  /// The expiration date of the certificate in &apos;Y-m-d&apos; format
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expirationDate")]
  public string? ExpirationDate { get; set; }

  /// <summary>
  /// The domain ssl certificate id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal? Id { get; set; }

  /// <summary>
  /// The type of issuer of this certificate. non-free or letsencrypt
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("issuerType")]
  public string? IssuerType { get; set; }
}
