//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// InvoiceItem from OpenAPI schema.
/// Schema path: #/components/schemas/InvoiceItem
/// </summary>
public partial class InvoiceItem
{
  /// <summary>
  /// Date when the order line item was up for invoicing
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public string? Date { get; set; }

  /// <summary>
  /// Product description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Applied discounts
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("discounts")]
  public List<object?>? Discounts { get; set; }

  /// <summary>
  /// Payment is recurring
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isRecurring")]
  public bool IsRecurring { get; set; }

  /// <summary>
  /// Price excluding VAT (displayed in cents)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("price")]
  public decimal Price { get; set; }

  /// <summary>
  /// Price including VAT (displayed in cents)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("priceInclVat")]
  public decimal PriceInclVat { get; set; }

  /// <summary>
  /// Product name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("product")]
  public string? Product { get; set; }

  /// <summary>
  /// Quantity
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quantity")]
  public decimal Quantity { get; set; }

  /// <summary>
  /// Amount of VAT charged
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("vat")]
  public decimal Vat { get; set; }

  /// <summary>
  /// Percentage used to calculate the VAT
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("vatPercentage")]
  public decimal VatPercentage { get; set; }
}
