//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// Invoice from OpenAPI schema.
/// Schema path: #/components/schemas/Invoice
/// </summary>
public partial class Invoice
{
  /// <summary>
  /// Invoice creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public string? CreationDate { get; set; }

  /// <summary>
  /// Currency used for this invoice
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("currency")]
  public string? Currency { get; set; }

  /// <summary>
  /// Invoice deadline
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("dueDate")]
  public string? DueDate { get; set; }

  /// <summary>
  /// Invoice number
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("invoiceNumber")]
  public string? InvoiceNumber { get; set; }

  /// <summary>
  /// Invoice status
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("invoiceStatus")]
  public string? InvoiceStatus { get; set; }

  /// <summary>
  /// Invoice paid date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("payDate")]
  public string? PayDate { get; set; }

  /// <summary>
  /// Invoice total (displayed in cents)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("totalAmount")]
  public decimal TotalAmount { get; set; }

  /// <summary>
  /// Invoice total including VAT (displayed in cents)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("totalAmountInclVat")]
  public decimal TotalAmountInclVat { get; set; }
}
