//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancerStatusReport from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancerStatusReport
/// </summary>
public partial class KubernetesLoadBalancerStatusReport
{
  /// <summary>
  /// IP version 4/6
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipVersion")]
  public decimal? IpVersion { get; set; }

  /// <summary>
  /// Last change in the state in Europe/Amsterdam timezone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lastChange")]
  public string? LastChange { get; set; }

  /// <summary>
  /// The IP address of the upstream load balancer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("loadBalancerIp")]
  public string? LoadBalancerIp { get; set; }

  /// <summary>
  /// The name of the upstream load balancer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("loadBalancerName")]
  public string? LoadBalancerName { get; set; }

  /// <summary>
  /// IP of the node that this report is for
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodeIpAddress")]
  public string? NodeIpAddress { get; set; }

  /// <summary>
  /// UUID of the node that this report is for
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodeUuid")]
  public string? NodeUuid { get; set; }

  /// <summary>
  /// Port
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public decimal? Port { get; set; }

  /// <summary>
  /// The state of this configuration, either &apos;up&apos; or &apos;down&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }
}
