//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancerBalancing from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancerBalancing
/// </summary>
public partial class KubernetesLoadBalancerBalancing
{
  /// <summary>
  /// LoadBalancer balancing cookie name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("cookieName")]
  public string? CookieName { get; set; }

  /// <summary>
  /// LoadBalancer balancing mode, either roundrobin, cookie, source
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public string? Mode { get; set; }
}
