//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancer from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancer
/// </summary>
public partial class KubernetesLoadBalancer
{
  [System.Text.Json.Serialization.JsonPropertyName("aggregatedStatus")]
  public KubernetesLoadBalancerAggregatedStatus? AggregatedStatus { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("balancing")]
  public KubernetesLoadBalancerBalancing? Balancing { get; set; }

  /// <summary>
  /// LoadBalancer IPv4 address
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv4Address")]
  public string? Ipv4Address { get; set; }

  /// <summary>
  /// LoadBalancer IPv6 address
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv6Address")]
  public string? Ipv6Address { get; set; }

  /// <summary>
  /// User configurable unique identifier (max 64 chars)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// A mapping between IP addresses and UUIDs of attached nodes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodes")]
  public string? Nodes { get; set; }

  /// <summary>
  /// LoadBalancer ports.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ports")]
  public List<object?>? Ports { get; set; }

  /// <summary>
  /// The name of the service
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("serviceName")]
  public string? ServiceName { get; set; }

  /// <summary>
  /// Defines the namespace the service is residing in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("serviceNamespace")]
  public string? ServiceNamespace { get; set; }

  /// <summary>
  /// LoadBalancer status, either &apos;active&apos;, &apos;creating&apos; or &apos;deleting&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// LoadBalancer Uuid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
