//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesPortConfiguration from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesPortConfiguration
/// </summary>
public class KubernetesPortConfiguration
{
  /// <summary>
  /// The mode determining how traffic between our load balancers and your attached IP address(es) is encrypted: &apos;off&apos;, &apos;on&apos;, &apos;strict&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("endpointSslMode")]
  public string? EndpointSslMode { get; set; }

  /// <summary>
  /// The mode determining how traffic is processed and forwarded: &apos;tcp&apos;, &apos;http&apos;, &apos;https&apos;, &apos;http2_https&apos;, &apos;proxy&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public string? Mode { get; set; }

  /// <summary>
  /// A name describing the port
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The port at which traffic arrives on your HA-IP
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sourcePort")]
  public decimal SourcePort { get; set; }

  /// <summary>
  /// The port at which traffic arrives on your attached IP address(es)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("targetPort")]
  public decimal TargetPort { get; set; }
}
