//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancerConfig from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancerConfig
/// </summary>
public partial class KubernetesLoadBalancerConfig
{
  /// <summary>
  /// The interval in milliseconds at which health checks are performed. The interval may not be smaller than 2000ms.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("healthCheckInterval")]
  public decimal? HealthCheckInterval { get; set; }

  /// <summary>
  /// The path (URI) of the page to check HTTP status code on
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("httpHealthCheckPath")]
  public string? HttpHealthCheckPath { get; set; }

  /// <summary>
  /// The port to perform the HTTP check on, this should be the port your services are listening on
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("httpHealthCheckPort")]
  public decimal? HttpHealthCheckPort { get; set; }

  /// <summary>
  /// Whether to use SSL when performing the HTTP check
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("httpHealthCheckSsl")]
  public bool? HttpHealthCheckSsl { get; set; }

  /// <summary>
  /// The IPs attached to this LoadBalancer
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ipAddresses")]
  public List<object?>? IpAddresses { get; set; }

  /// <summary>
  /// LoadBalancer IP setup: &apos;both&apos;, &apos;noipv6&apos;, &apos;ipv6to4&apos;, &apos;ipv4to6&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipSetup")]
  public string? IpSetup { get; set; }

  /// <summary>
  /// LoadBalancer load balancing mode: &apos;roundrobin&apos;, &apos;cookie&apos;, &apos;source&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("loadBalancingMode")]
  public string? LoadBalancingMode { get; set; }

  /// <summary>
  /// Array with port configurations for this LoadBalancer
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("portConfiguration")]
  public List<object?>? PortConfiguration { get; set; }

  /// <summary>
  /// The PTR record for the LoadBalancer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ptrRecord")]
  public string? PtrRecord { get; set; }

  /// <summary>
  /// Cookie name to pin sessions on when using cookie balancing mode
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("stickyCookieName")]
  public string? StickyCookieName { get; set; }

  /// <summary>
  /// LoadBalancer TLS Mode: &apos;tls10_11_12&apos;, &apos;tls11_12&apos;, &apos;tls12&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tlsMode")]
  public string? TlsMode { get; set; }
}
