//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancerAggregatedStatus from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancerAggregatedStatus
/// </summary>
public partial class KubernetesLoadBalancerAggregatedStatus
{
  /// <summary>
  /// LoadBalancer&apos;s total amount of nodes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public decimal? Total { get; set; }

  /// <summary>
  /// LoadBalancer&apos;s amount of healthy nodes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("up")]
  public decimal? Up { get; set; }
}
