//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesEvent from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesEvent
/// </summary>
public class KubernetesEvent
{
  /// <summary>
  /// The amount of times the event occured
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public decimal? Count { get; set; }

  /// <summary>
  /// Unix timestamp of when the event was created
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("creationTimestamp")]
  public decimal? CreationTimestamp { get; set; }

  /// <summary>
  /// Unix timestamp of when the event was first see
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("firstTimestamp")]
  public decimal? FirstTimestamp { get; set; }

  /// <summary>
  /// The kind of object this event is about
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("involvedObjectKind")]
  public string? InvolvedObjectKind { get; set; }

  /// <summary>
  /// The name of the object this event is about
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("involvedObjectName")]
  public string? InvolvedObjectName { get; set; }

  /// <summary>
  /// Unix timestamp of when the event was last seen
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lastTimestamp")]
  public decimal? LastTimestamp { get; set; }

  /// <summary>
  /// A mesage about the event
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  /// <summary>
  /// The name of the event
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The namespace of the event
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("namespace")]
  public string? Namespace { get; set; }

  /// <summary>
  /// The reason for the event
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reason")]
  public string? Reason { get; set; }

  /// <summary>
  /// The emitter of this event
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceComponent")]
  public string? SourceComponent { get; set; }

  /// <summary>
  /// The type of event, e.g: Warning or Normal
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
