//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesProductSpec from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesProductSpec
/// </summary>
public class KubernetesProductSpec
{
  /// <summary>
  /// amount of the specification
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// Description of the specification
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Name of the specification
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Specifies in what unit the amount is
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("unit")]
  public string? Unit { get; set; }
}
