//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// KubernetesProductPeriodPrice from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesProductPeriodPrice
/// </summary>
public partial class KubernetesProductPeriodPrice
{
  /// <summary>
  /// The costs for the period described in this object
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("costCents")]
  public string? CostCents { get; set; }

  /// <summary>
  /// The currency of the costs described in this object
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency")]
  public string? Currency { get; set; }

  /// <summary>
  /// Whether the costs in this object is exact or an approximation
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isExact")]
  public bool? IsExact { get; set; }

  /// <summary>
  /// The amount of the period this object describes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("periodLength")]
  public decimal? PeriodLength { get; set; }

  /// <summary>
  /// The unit of the period this object describes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("periodUnit")]
  public string? PeriodUnit { get; set; }
}
