//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesBlockStorageSnapshot from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesBlockStorageSnapshot
/// </summary>
public partial class KubernetesBlockStorageSnapshot
{
  /// <summary>
  /// Name of the volume this snapshot belongs to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("blockStorageName")]
  public string? BlockStorageName { get; set; }

  /// <summary>
  /// Name of the cluster this snapshot belongs to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clusterName")]
  public string? ClusterName { get; set; }

  /// <summary>
  /// Creating datetime of a the snapshot
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public string? CreationDate { get; set; }

  /// <summary>
  /// User configurable unique identifier (max 64 chars)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Size of snapshot in gibibytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sizeInGib")]
  public decimal? SizeInGib { get; set; }

  /// <summary>
  /// Status of the volume  &apos;creating&apos;, &apos;ready&apos;, &apos;reverting&apos;, &apos;deleting&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Uuid of the snapshot
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
