//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesLoadBalancerPort from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesLoadBalancerPort
/// </summary>
public class KubernetesLoadBalancerPort
{
  /// <summary>
  /// LoadBalancer port mode, either tcp, http, https, http2_https or proxy
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public string? Mode { get; set; }

  /// <summary>
  /// LoadBalancer port name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// LoadBalancer port
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public decimal? Port { get; set; }
}
