//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// KubernetesIpAddress from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesIpAddress
/// </summary>
public partial class KubernetesIpAddress
{
  /// <summary>
  /// The IP address
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("address")]
  public string? Address { get; set; }

  /// <summary>
  /// Subnet mask
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("subnetMask")]
  public string? SubnetMask { get; set; }

  /// <summary>
  /// external|internal|private
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
