//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// KubeConfig from OpenAPI schema.
/// Schema path: #/components/schemas/KubeConfig
/// </summary>
public partial class KubeConfig
{
  /// <summary>
  /// KubeConfig base64 encoded YAML
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("encodedYaml")]
  public string? EncodedYaml { get; set; }
}
