//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// KubernetesNode from OpenAPI schema.
/// Schema path: #/components/schemas/KubernetesNode
/// </summary>
public partial class KubernetesNode
{
  /// <summary>
  /// Name of the cluster the node is in
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clusterName")]
  public string? ClusterName { get; set; }

  /// <summary>
  /// IP addresses assigned to this node
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipAddresses")]
  public List<object?>? IpAddresses { get; set; }

  /// <summary>
  /// Uuid of the nodePool the node is in
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("nodePoolUuid")]
  public string? NodePoolUuid { get; set; }

  /// <summary>
  /// Status of the Node
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Uuid of the Node
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
