//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// LicenseKey from OpenAPI schema.
/// Schema path: #/components/schemas/LicenseKey
/// </summary>
public partial class LicenseKey
{
  /// <summary>
  /// License key
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  /// <summary>
  /// License key name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
