//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// Licenses from OpenAPI schema.
/// Schema path: #/components/schemas/Licenses
/// </summary>
public partial class Licenses
{
  /// <summary>
  /// A list of licenses active on your VPS
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("active")]
  public List<object?>? Active { get; set; }

  /// <summary>
  /// A list of available licenses that you can order or switch to for your VPS
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("available")]
  public List<object?>? Available { get; set; }

  /// <summary>
  /// A list of licenses active on your VPS that you can cancel
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("cancellable")]
  public List<object?>? Cancellable { get; set; }
}
