//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// LicenseProduct from OpenAPI schema.
/// Schema path: #/components/schemas/LicenseProduct
/// </summary>
public partial class LicenseProduct
{
  /// <summary>
  /// Whether this license is the default
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isDefault")]
  public bool IsDefault { get; set; }

  /// <summary>
  /// Maximum quantity you are allowed to purchase
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("maxQuantity")]
  public decimal MaxQuantity { get; set; }

  /// <summary>
  /// Minimum quantity you have to purchase
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("minQuantity")]
  public decimal MinQuantity { get; set; }

  /// <summary>
  /// License name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Price in cents
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("price")]
  public decimal Price { get; set; }

  /// <summary>
  /// Recurring price in cents
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("recurringPrice")]
  public decimal RecurringPrice { get; set; }

  /// <summary>
  /// License type: &apos;operating-system&apos;, &apos;addon&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
