//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// MailAddon from OpenAPI schema.
/// Schema path: #/components/schemas/MailAddon
/// </summary>
public class MailAddon
{
  /// <summary>
  /// Indication of whether this addon can be linked, any addons that do not add extra disk space cannot be linked.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("canBeLinked")]
  public bool CanBeLinked { get; set; }

  /// <summary>
  /// The amount of extra disk space this addon adds
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskSpace")]
  public decimal DiskSpace { get; set; }

  /// <summary>
  /// Identifier for the EmailAddon
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal Id { get; set; }

  /// <summary>
  /// The mailbox that this addon is linked to
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("linkedMailBox")]
  public string? LinkedMailBox { get; set; }

  /// <summary>
  /// The amount of extra mailboxes this addon adds
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mailboxes")]
  public decimal Mailboxes { get; set; }
}
