//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// MailServiceInformation from OpenAPI schema.
/// Schema path: #/components/schemas/MailServiceInformation
/// </summary>
public class MailServiceInformation
{
  /// <summary>
  /// x-transip-mail-auth DNS TXT record Value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dnsTxt")]
  public string? DnsTxt { get; set; }

  /// <summary>
  /// The password of the mail service
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The quota of the mail service
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("quota")]
  public decimal? Quota { get; set; }

  /// <summary>
  /// The usage of the mail service
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("usage")]
  public decimal? Usage { get; set; }

  /// <summary>
  /// The username of the mail service
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
