//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// MailForward from OpenAPI schema.
/// Schema path: #/components/schemas/MailForward
/// </summary>
public class MailForward
{
  /// <summary>
  /// The domain to forward (will be combined with the alias to make the full email address).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("domain")]
  public string? Domain { get; set; }

  /// <summary>
  /// The email address to forward to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("forwardTo")]
  public string? ForwardTo { get; set; }

  /// <summary>
  /// Unique identifier of the MailForward
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// local part of the mailbox for the forward
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("localPart")]
  public string? LocalPart { get; set; }

  /// <summary>
  /// Status of the forward.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
