//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// MailPackage from OpenAPI schema.
/// Schema path: #/components/schemas/MailPackage
/// </summary>
public partial class MailPackage
{
  /// <summary>
  /// Domain of the EmailPackage
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("domain")]
  public string? Domain { get; set; }

  /// <summary>
  /// Current status of the EmailPackage
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
