//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// Mailbox from OpenAPI schema.
/// Schema path: #/components/schemas/Mailbox
/// </summary>
public partial class Mailbox
{
  /// <summary>
  /// Disk space that is available for the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("availableDiskSpace")]
  public string? AvailableDiskSpace { get; set; }

  /// <summary>
  /// Domain of the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("domain")]
  public string? Domain { get; set; }

  /// <summary>
  /// Email address to also forward the email to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("forwardTo")]
  public string? ForwardTo { get; set; }

  /// <summary>
  /// Identifier for the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  /// <summary>
  /// IMAP port for IMAP server
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imapPort")]
  public string? ImapPort { get; set; }

  /// <summary>
  /// IMAP server for mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imapServer")]
  public string? ImapServer { get; set; }

  /// <summary>
  /// Shows whether a mailbox is locked
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isLocked")]
  public string? IsLocked { get; set; }

  /// <summary>
  /// Local part of the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("localPart")]
  public string? LocalPart { get; set; }

  /// <summary>
  /// POP3 port for IMAP server
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pop3Port")]
  public string? Pop3Port { get; set; }

  /// <summary>
  /// POP3 server for mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pop3Server")]
  public string? Pop3Server { get; set; }

  /// <summary>
  /// SMTP port for SMTP server
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("smtpPort")]
  public string? SmtpPort { get; set; }

  /// <summary>
  /// SMTP server for mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("smtpServer")]
  public string? SmtpServer { get; set; }

  /// <summary>
  /// Current status of the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Disk space that is used for the mailbox
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usedDiskSpace")]
  public string? UsedDiskSpace { get; set; }

  /// <summary>
  /// Webmail url
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("webmailUrl")]
  public string? WebmailUrl { get; set; }
}
