//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// Nameserver from OpenAPI schema.
/// Schema path: #/components/schemas/Nameserver
/// </summary>
public class Nameserver
{
  /// <summary>
  /// The hostname of this nameserver
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hostname")]
  public string? Hostname { get; set; }

  /// <summary>
  /// Optional ipv4 glue record for this nameserver
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv4")]
  public string? Ipv4 { get; set; }

  /// <summary>
  /// Optional ipv6 glue record for this nameserver
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv6")]
  public string? Ipv6 { get; set; }
}
