//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// ObjectstoreQuota from OpenAPI schema.
/// Schema path: #/components/schemas/ObjectstoreQuota
/// </summary>
public class ObjectstoreQuota
{
  /// <summary>
  /// The active quota in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bytesQuota")]
  public decimal? BytesQuota { get; set; }

  /// <summary>
  /// The consumed quota in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bytesUsed")]
  public decimal? BytesUsed { get; set; }

  /// <summary>
  /// The unique project id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("projectId")]
  public string? ProjectId { get; set; }
}
