//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// ObjectStoreToken from OpenAPI schema.
/// Schema path: #/components/schemas/ObjectStoreToken
/// </summary>
public partial class ObjectStoreToken
{
  /// <summary>
  /// Object Store access key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("accessKey")]
  public string? AccessKey { get; set; }

  /// <summary>
  /// Object Store management url
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("managementUrl")]
  public string? ManagementUrl { get; set; }

  /// <summary>
  /// Object Store project id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("projectId")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// Object Store secret key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("secretKey")]
  public string? SecretKey { get; set; }

  /// <summary>
  /// S3 token id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tokenId")]
  public string? TokenId { get; set; }

  /// <summary>
  /// Token user id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }
}
