//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// OpenStackProject from OpenAPI schema.
/// Schema path: #/components/schemas/OpenStackProject
/// </summary>
public partial class OpenStackProject
{
  /// <summary>
  /// Describes this project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The domain in which a project is stored.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("domain")]
  public string? Domain { get; set; }

  /// <summary>
  /// The unique project id, this identifier can be used to modify a project and modify access permissions for users
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Set to true when a project has been administratively blocked
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isBlocked")]
  public bool? IsBlocked { get; set; }

  /// <summary>
  /// When an ongoing process blocks the project from being modified, this is set to true
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isLocked")]
  public bool? IsLocked { get; set; }

  /// <summary>
  /// Name of the project
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The region in which a project is stored.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("region")]
  public string? Region { get; set; }

  /// <summary>
  /// Type of the project, either &apos;objectstore&apos; or &apos;openstack&apos; defaults to &apos;openstack&apos; when not specified
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
