//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// OpenStackUser from OpenAPI schema.
/// Schema path: #/components/schemas/OpenStackUser
/// </summary>
public class OpenStackUser
{
  /// <summary>
  /// Description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Email address
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// Identifier
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Whether TOTP (Time-based One-Time Password) is enabled, e.g., true
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("totpEnabled")]
  public bool TotpEnabled { get; set; }

  /// <summary>
  /// Login name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
