//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// PrivateNetworkVps from OpenAPI schema.
/// Schema path: #/components/schemas/PrivateNetworkVps
/// </summary>
public partial class PrivateNetworkVps
{
  /// <summary>
  /// The name that can be set by customer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// If the VPS is administratively blocked
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isBlocked")]
  public bool? IsBlocked { get; set; }

  /// <summary>
  /// If this VPS is locked by the customer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isCustomerLocked")]
  public bool? IsCustomerLocked { get; set; }

  /// <summary>
  /// Whether or not another process is already doing stuff with this VPS
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isLocked")]
  public bool? IsLocked { get; set; }

  /// <summary>
  /// The VPS macaddress
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("macAddress")]
  public string? MacAddress { get; set; }

  /// <summary>
  /// The unique VPS name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The unique identifier for the VPS
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
