//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// Product from OpenAPI schema.
/// Schema path: #/components/schemas/Product
/// </summary>
public partial class Product
{
  /// <summary>
  /// Describes this product
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Name of the product
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Price in cents
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("price")]
  public decimal? Price { get; set; }

  /// <summary>
  /// The recurring price for the product in cents
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("recurringPrice")]
  public decimal? RecurringPrice { get; set; }
}
