//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// RevertBlockStorageBackupRequest (generated from inline request body).
/// Source: PATCH /block-storages/{blockStorageIdentifier}/backups/{backupId} (requestBody)
/// </summary>
public partial class RevertBlockStorageBackupRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  /// <summary>
  /// When set, revert the backup to this block storage
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("destinationBlockStorageName")]
  public string? DestinationBlockStorageName { get; set; }
}
