//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// SetHAIPAttachedIPAddressesRequest from OpenAPI schema.
/// Schema path: #/components/schemas/SetHAIPAttachedIPAddressesRequest
/// </summary>
public class SetHAIPAttachedIPAddressesRequest
{
  /// <summary>
  /// Set of IP addresses to attach, replaces the current set of IP addresses
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ipAddresses")]
  public List<object>? IpAddresses { get; set; }
}
