//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// SettingValue from OpenAPI schema.
/// Schema path: #/components/schemas/SettingValue
/// </summary>
public partial class SettingValue
{
  /// <summary>
  /// Boolean Value
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("valueBoolean")]
  public bool ValueBoolean { get; set; }

  /// <summary>
  /// String Value
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("valueString")]
  public string? ValueString { get; set; }
}
