//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// Setting from OpenAPI schema.
/// Schema path: #/components/schemas/Setting
/// </summary>
public partial class Setting
{
  /// <summary>
  /// Setting Datatype
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dataType")]
  public string? DataType { get; set; }

  /// <summary>
  /// Setting Name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Setting ReadOnly
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("readOnly")]
  public bool? ReadOnly { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public SettingValue Value { get; set; } = null!;
}
