//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// Snapshot from OpenAPI schema.
/// Schema path: #/components/schemas/Snapshot
/// </summary>
public partial class Snapshot
{
  /// <summary>
  /// The snapshot creation date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeCreate")]
  public string? DateTimeCreate { get; set; }

  /// <summary>
  /// The snapshot description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The size of the snapshot in kB
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("diskSize")]
  public decimal? DiskSize { get; set; }

  /// <summary>
  /// The snapshot name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The snapshot OperatingSystem
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("operatingSystem")]
  public string? OperatingSystem { get; set; }

  /// <summary>
  /// The snapshot status (&apos;active&apos;, &apos;creating&apos;, &apos;reverting&apos;, &apos;deleting&apos;, &apos;pendingDeletion&apos;, &apos;syncing&apos;, &apos;moving&apos;)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
