//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// SshKey from OpenAPI schema.
/// Schema path: #/components/schemas/SshKey
/// </summary>
public partial class SshKey
{
  /// <summary>
  /// Date when this SSH key was added (TimeZone: Europe/Amsterdam)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public string? CreationDate { get; set; }

  /// <summary>
  /// SSH key description (max 255 chars)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// MD5 fingerprint of SSH key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fingerprint")]
  public string? Fingerprint { get; set; }

  /// <summary>
  /// SSH key identifier
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal Id { get; set; }

  /// <summary>
  /// Whether or not the key is flagged as default
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isDefault")]
  public bool IsDefault { get; set; }

  /// <summary>
  /// SSH key
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }
}
