//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// SslCertificate from OpenAPI schema.
/// Schema path: #/components/schemas/SslCertificate
/// </summary>
public partial class SslCertificate
{
  /// <summary>
  /// Whether the certificate can be reissued
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("canReissue")]
  public string? CanReissue { get; set; }

  /// <summary>
  /// The id of the certificate, can be used to retrieve additional info
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("certificateId")]
  public decimal CertificateId { get; set; }

  /// <summary>
  /// The domain name that the SSL certificate is added to. Start with &apos;*.&apos; when the certificate is a wildcard.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("commonName")]
  public string? CommonName { get; set; }

  /// <summary>
  /// Expiration date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("expirationDate")]
  public string? ExpirationDate { get; set; }

  /// <summary>
  /// Order date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("orderDate")]
  public string? OrderDate { get; set; }

  /// <summary>
  /// The current status, either &apos;active&apos;, &apos;inactive&apos;, &apos;busy&apos; or &apos;expired&apos; &lt;br /&gt; &lt;br /&gt; &lt;b&gt;Active&lt;/b&gt;: Certificate is not expired and can be used &lt;br /&gt; &lt;b&gt;Inactive&lt;/b&gt;: Certificate is being processed &lt;br /&gt; &lt;b&gt;Busy&lt;/b&gt;: Order is in progress &lt;br /&gt; &lt;b&gt;Expired&lt;/b&gt;: Certificate is malformed or gone.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
