//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// TenantUsage from OpenAPI schema.
/// Schema path: #/components/schemas/TenantUsage
/// </summary>
public class TenantUsage
{
  /// <summary>
  /// The current usage of your acronis product
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currentUsage")]
  public string? CurrentUsage { get; set; }

  /// <summary>
  /// The usage limit of your acronis product
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("limit")]
  public string? Limit { get; set; }

  /// <summary>
  /// The usage name of your acronis product
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
