//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// Tenant from OpenAPI schema.
/// Schema path: #/components/schemas/Tenant
/// </summary>
public partial class Tenant
{
  /// <summary>
  /// description of the tenant
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// count of available edr endpoints for the tenant
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("edrEndpoints")]
  public decimal? EdrEndpoints { get; set; }

  /// <summary>
  /// if this tenant is in self managed mode
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isSelfManaged")]
  public bool? IsSelfManaged { get; set; }

  /// <summary>
  /// tenant (string, optional) - name of the tenant
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// storage size of the tenant in GB
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("storageSizeInGB")]
  public decimal? StorageSizeInGB { get; set; }

  /// <summary>
  /// uuid for this tenant
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
