//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// TransferDomainRequest (generated from inline request body).
/// Source: POST /domains (requestBody)
/// </summary>
public partial class TransferDomainRequest
{
  /// <summary>
  /// The auth code of the domain.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("authCode")]
  public string? AuthCode { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("contacts")]
  public List<object>? Contacts { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("dnsEntries")]
  public List<object>? DnsEntries { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("domainName")]
  public string? DomainName { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("nameservers")]
  public List<object>? Nameservers { get; set; }
}
