//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// UpdateNodepoolRequestNodePool from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateNodepoolRequestNodePool
/// </summary>
public partial class UpdateNodepoolRequestNodePool
{
  /// <summary>
  /// Whether autoscaling is enabled for this NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("autoscalingEnabled")]
  public bool? AutoscalingEnabled { get; set; }

  /// <summary>
  /// The availabilityZone the nodes of this nodePool are in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// Name of the cluster the nodePool is in
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clusterName")]
  public string? ClusterName { get; set; }

  /// <summary>
  /// cluster (string, optional) - Describes this NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The desired amount of nodes in this pool, might not always be the actual count of nodes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("desiredNodeCount")]
  public decimal DesiredNodeCount { get; set; }

  /// <summary>
  /// Maximum amount of nodes when autoscaling is enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxNodeCount")]
  public decimal? MaxNodeCount { get; set; }

  /// <summary>
  /// Minimum amount of nodes when autoscaling is enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("minNodeCount")]
  public decimal? MinNodeCount { get; set; }

  /// <summary>
  /// The specification of the Nodes in this NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodeSpec")]
  public string? NodeSpec { get; set; }

  /// <summary>
  /// Nodes currently in NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodes")]
  public List<object>? Nodes { get; set; }

  /// <summary>
  /// The NodePool status
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Uuid of the NodePool
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uuid")]
  public string? Uuid { get; set; }
}
