//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// UpdateMailboxFieldRequest (generated from inline request body).
/// Source: PATCH /email/{domain}/mailboxes/{identifier} (requestBody)
/// </summary>
public partial class UpdateMailboxFieldRequest
{
  /// <summary>
  /// The target email to forward to
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("forwardTo")]
  public string? ForwardTo { get; set; }

  /// <summary>
  /// Size of the mailbox in MB
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("maxDiskUsage")]
  public decimal? MaxDiskUsage { get; set; }

  /// <summary>
  /// The password for the mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }
}
