//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// UpdatePrivateNetworkRequestPrivateNetwork from OpenAPI schema.
/// Schema path: #/components/schemas/UpdatePrivateNetworkRequestPrivateNetwork
/// </summary>
public partial class UpdatePrivateNetworkRequestPrivateNetwork
{
  /// <summary>
  /// The VPSes in this private network
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("connectedVpses")]
  public List<object>? ConnectedVpses { get; set; }

  /// <summary>
  /// The custom name that can be set by customer
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// If the Private Network is administratively blocked
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isBlocked")]
  public bool? IsBlocked { get; set; }

  /// <summary>
  /// When locked, another process is already working with this private network
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isLocked")]
  public bool? IsLocked { get; set; }

  /// <summary>
  /// The unique private network name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The names of VPSes in this private network
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("vpsNames")]
  public List<object>? VpsNames { get; set; }
}
