//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// UpgradeBlockStorageRequest (generated from inline request body).
/// Source: POST /block-storages (requestBody)
/// </summary>
public partial class UpgradeBlockStorageRequest
{
  /// <summary>
  /// The name of the blockstorage to upgrade
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("blockStorageName")]
  public string? BlockStorageName { get; set; }

  /// <summary>
  /// Whether to order offsite backups, omit this to use current value
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("offsiteBackups")]
  public bool? OffsiteBackups { get; set; }

  /// <summary>
  /// The size of the block storage in KB.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("size")]
  public decimal? Size { get; set; }
}
