//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsBackup from OpenAPI schema.
/// Schema path: #/components/schemas/VpsBackup
/// </summary>
public class VpsBackup
{
  /// <summary>
  /// The name of the availability zone the backup is in
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// The backup creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeCreate")]
  public string? DateTimeCreate { get; set; }

  /// <summary>
  /// The backup disk size in kB
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskSize")]
  public decimal DiskSize { get; set; }

  /// <summary>
  /// The backup id
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public decimal Id { get; set; }

  /// <summary>
  /// The backup operatingSystem
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("operatingSystem")]
  public string? OperatingSystem { get; set; }

  /// <summary>
  /// The backup retention type (daily, weekly)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("retentionType")]
  public string? RetentionType { get; set; }

  /// <summary>
  /// Status of the backup (&apos;active&apos;, &apos;creating&apos;, &apos;reverting&apos;, &apos;deleting&apos;, &apos;pendingDeletion&apos;, &apos;syncing&apos;, &apos;moving&apos;)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }
}
