//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsFirewallRule from OpenAPI schema.
/// Schema path: #/components/schemas/VpsFirewallRule
/// </summary>
public class VpsFirewallRule
{
  /// <summary>
  /// The rule name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The end port of this firewall rule
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("endPort")]
  public decimal EndPort { get; set; }

  /// <summary>
  /// The protocol tcp ,  udp or tcp_udp
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  /// <summary>
  /// The start port of this firewall rule
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("startPort")]
  public decimal StartPort { get; set; }

  /// <summary>
  /// Whitelisted IP&apos;s or ranges that are allowed to connect, empty to allow all
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("whitelist")]
  public List<object?>? Whitelist { get; set; }
}
