//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsOrder from OpenAPI schema.
/// Schema path: #/components/schemas/VpsOrder
/// </summary>
public class VpsOrder
{
  /// <summary>
  /// Array with additional addons
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("addons")]
  public List<object?>? Addons { get; set; }

  /// <summary>
  /// The name of the availability zone where the vps should be created
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("availabilityZone")]
  public string? AvailabilityZone { get; set; }

  /// <summary>
  /// Base64 encoded preseed / kickstart instructions, when installing unattended. The decoded string may be up to 49152 bytes (48 KiB) long.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("base64InstallText")]
  public string? Base64InstallText { get; set; }

  /// <summary>
  /// The description of the VPS
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The hashedPassword for the specified user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hashedPassword")]
  public string? HashedPassword { get; set; }

  /// <summary>
  /// The name for the host, only needed for installing a preinstallable control panel image
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hostname")]
  public string? Hostname { get; set; }

  /// <summary>
  /// The flavour of OS installation installer, preinstallable or cloudinit check GET OperatingSystem to see what flavours your OS supports
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("installFlavour")]
  public string? InstallFlavour { get; set; }

  /// <summary>
  /// Licenses you want to add to your preinstallable installation flavor
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("licenses")]
  public List<object?>? Licenses { get; set; }

  /// <summary>
  /// The name of the operating system to install
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("operatingSystem")]
  public string? OperatingSystem { get; set; }

  /// <summary>
  /// Name of the product
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("productName")]
  public string? ProductName { get; set; }

  /// <summary>
  /// Array of public ssh key&apos;s to use for account creating during installation
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sshKeys")]
  public List<object?>? SshKeys { get; set; }

  /// <summary>
  /// VPS User
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
