//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsUsageDataCpu from OpenAPI schema.
/// Schema path: #/components/schemas/VpsUsageDataCpu
/// </summary>
public partial class VpsUsageDataCpu
{
  /// <summary>
  /// Date of the entry, by default in UNIX timestamp format
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public decimal Date { get; set; }

  /// <summary>
  /// The percentage of CPU usage for this entry
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("percentage")]
  public decimal Percentage { get; set; }
}
