//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// VpsUsageDataNetwork from OpenAPI schema.
/// Schema path: #/components/schemas/VpsUsageDataNetwork
/// </summary>
public partial class VpsUsageDataNetwork
{
  /// <summary>
  /// Date of the entry, by default in UNIX timestamp format
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public decimal Date { get; set; }

  /// <summary>
  /// The amount of inbound traffic in Mbps for this usage entry
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mbitIn")]
  public decimal MbitIn { get; set; }

  /// <summary>
  /// The amount of outbound traffic in Mbps for this usage entry
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mbitOut")]
  public decimal MbitOut { get; set; }
}
