//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsUsageDataDisk from OpenAPI schema.
/// Schema path: #/components/schemas/VpsUsageDataDisk
/// </summary>
public partial class VpsUsageDataDisk
{
  /// <summary>
  /// Date of the entry, by default in UNIX timestamp format
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public decimal Date { get; set; }

  /// <summary>
  /// The read IOPS for this entry
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("iopsRead")]
  public decimal IopsRead { get; set; }

  /// <summary>
  /// The write IOPS for this entry
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("iopsWrite")]
  public decimal IopsWrite { get; set; }
}
