//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Transip.Models;

/// <summary>
/// VpsVncData from OpenAPI schema.
/// Schema path: #/components/schemas/VpsVncData
/// </summary>
public partial class VpsVncData
{
  /// <summary>
  /// Location of the VNC Proxy
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("host")]
  public string? Host { get; set; }

  /// <summary>
  /// Password to setup up the VNC connection (changes dynamically)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Websocket path including the token
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("path")]
  public string? Path { get; set; }

  /// <summary>
  /// Token to identify the VPS to connect to (changes dynamically)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  /// <summary>
  /// Complete websocket URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }
}
