//
// <auto-generated>
// TransIP API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/transip.yaml
// API: TransIP API
// Version: 6.53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.TransIp.Models;

/// <summary>
/// WhoisContact from OpenAPI schema.
/// Schema path: #/components/schemas/WhoisContact
/// </summary>
public partial class WhoisContact
{
  /// <summary>
  /// The city part of the address of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// The kvk number of this Contact, in case of a company
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("companyKvk")]
  public string? CompanyKvk { get; set; }

  /// <summary>
  /// The companyName of this Contact, in case of a company
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("companyName")]
  public string? CompanyName { get; set; }

  /// <summary>
  /// The type number of this Contact, in case of a company. Possible types are: &apos;BV&apos;, &apos;BVI/O&apos;, &apos;COOP&apos;, &apos;CV&apos;, &apos;EENMANSZAAK&apos;, &apos;KERK&apos;, &apos;NV&apos;, &apos;OWM&apos;, &apos;REDR&apos;, &apos;STICHTING&apos;, &apos;VERENIGING&apos;, &apos;VOF&apos;, &apos;BEG&apos;, &apos;BRO&apos;, &apos;EESV&apos; and &apos;ANDERS&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("companyType")]
  public string? CompanyType { get; set; }

  /// <summary>
  /// The country of this Contact, one of the ISO 3166-1 2 letter country codes, must be lowercase.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// The email address of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The faxNumber of this Contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("faxNumber")]
  public string? FaxNumber { get; set; }

  /// <summary>
  /// The firstName of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("firstName")]
  public string? FirstName { get; set; }

  /// <summary>
  /// The lastName of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lastName")]
  public string? LastName { get; set; }

  /// <summary>
  /// The number part of the address of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// The phoneNumber of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("phoneNumber")]
  public string? PhoneNumber { get; set; }

  /// <summary>
  /// The postalCode part of the address of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("postalCode")]
  public string? PostalCode { get; set; }

  /// <summary>
  /// The street of the address of this Contact
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("street")]
  public string? Street { get; set; }

  /// <summary>
  /// The type of this Contact, &apos;registrant&apos;, &apos;administrative&apos; or &apos;technical&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }
}
